# Generated by Django 5.1.7 on 2025-03-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('game', models.CharField(blank=True, default='Valorant', max_length=200, null=True)),
                ('registration_deadline', models.DateTimeField()),
                ('image_url', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='event_images/')),
                ('event_external_url', models.URLField(blank=True, help_text='Optional', null=True)),
                ('stream_url', models.URLField(blank=True, help_text='Optional', null=True)),
                ('stream_type', models.URLField(blank=True, help_text='Optional', null=True)),
                ('event_rules', models.TextField(blank=True, help_text='Optional', null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventtype')),
            ],
        ),
    ]
