# Generated by Django 5.1.7 on 2025-03-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetails',
            options={'verbose_name': 'Event Detail', 'verbose_name_plural': 'Event Details'},
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='stream_type',
            field=models.CharField(blank=True, help_text='Optional', max_length=200, null=True),
        ),
    ]
