# Generated by Django 5.1.7 on 2025-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('scrims', 'Scrims'), ('watchparty', 'Watchparty'), ('giveaway', 'Giveaway')], max_length=50),
        ),
    ]
