# Generated by Django 5.1.7 on 2025-03-16 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_eventdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='game_icons/')),
                ('game_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Events.game'),
            preserve_default=False,
        ),
    ]
