# Generated by Django 5.1.7 on 2025-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_eventtype_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
