# Generated by Django 5.1.7 on 2025-03-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_game_alter_eventdetails_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default='PC', max_length=100),
            preserve_default=False,
        ),
    ]
