# Generated by Django 5.1.7 on 2025-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_eventdetails_status_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='teams',
            field=models.IntegerField(default=0),
        ),
    ]
