# Generated by Django 5.1.7 on 2025-03-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(upload_to='team_logos/')),
                ('player1', models.CharField(max_length=50)),
                ('player1_riot_id', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('player2_riot_id', models.CharField(max_length=50)),
                ('player3', models.CharField(max_length=50)),
                ('player3_riot_id', models.CharField(max_length=50)),
                ('player4', models.CharField(max_length=50)),
                ('player4_riot_id', models.CharField(max_length=50)),
                ('player5', models.CharField(max_length=50)),
                ('player5_riot_id', models.CharField(max_length=50)),
                ('player6', models.CharField(blank=True, max_length=50, null=True)),
                ('player6_riot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('player7', models.CharField(blank=True, max_length=50, null=True)),
                ('player7_riot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('registrant_email', models.EmailField(help_text='Your email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
